kind: pipeline
type: docker
name: default

trigger:
  branch:
    - master
  event:
    - push

volumes:
  - name: krcon
    host:
      path: /tmp/cache

steps:
  - name: restore-cache
    image: drillster/drone-volume-cache
    pull: if-not-exists
    settings:
      restore: true
      mount:
        - ./gradle_user_home
    volumes:
    - name: krcon
      path: /cache

  - name: build
    image: gradle:5.6.4
    pull: if-not-exists
    commands:
      - gradle shadowJar -i -g ./gradle_user_home

  - name: rebuild-cache
    image: drillster/drone-volume-cache
    pull: if-not-exists
    settings:
      rebuild: true
      mount:
        - ./gradle_user_home
    volumes:
      - name: krcon
        path: /cache
    when:
      status:
        - failure
        - success

  - name: local docker
    image: plugins/docker
    pull: if-not-exists
    settings:
      repo: 172.16.101.172:5500/shinobi9/drone-rcon
      registry: 172.16.101.172:5500
      tags: 0.0.1
      insecure: true

  - name: test
    image: 172.16.101.172:5500/shinobi9/drone-rcon:0.0.1
    pull: always
    settings:
      host:
        from_secret: RCON_HOST
      port:
        from_secret: RCON_PORT
      password:
        from_secret: RCON_PASSWORD
      commands:
      - "say hi"
      - "say how are you?"

  - name: publish
    image: plugins/docker
    pull: if-not-exists
    settings:
      repo: shinobi9/drone-rcon
      tags: latest
      username:
        from_secret: DOCKER_USERNAME
      password:
        from_secret: DOCKER_PASSWORD